
name: Deploy website

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd "Code/04 Artifacts & Outputs/01 Starting Project"
          npm ci

      - name: Lint code
        run: |
          cd "Code/04 Artifacts & Outputs/01 Starting Project"
          npm run lint

      - name: Test code
        run: |
          cd "Code/04 Artifacts & Outputs/01 Starting Project"
          npm run test

  build_site:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd "Code/04 Artifacts & Outputs/01 Starting Project"
          npm ci

      - name: Build website
        run: |
          cd "Code/04 Artifacts & Outputs/01 Starting Project"
          npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            Code/04 Artifacts & Outputs/01 Starting Project/dist
            Code/04 Artifacts & Outputs/01 Starting Project/package.json

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Output contents
        run: ls -R

      - name: Deploy
        run: echo "Deploying..."